# Site settings
title: Tech notes
email: anton@batiaev.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog about different subjects.
baseurl: "/blog"
url: "https://batiaev.com"
twitter_username: batiaev_com
github_username:  anbat
permalink: /:year/:month/:day/:title.html
copyright: '&copy; <time datetime="2013-03-13">2013 &ndash; 2016</time> Anton Batiaev'

# Build settings
markdown: kramdown
